import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "it" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    browseOffers: "Browse Offers",
    dashboard: "Dashboard",
    postOffer: "Post Offer",
    support: "Support",
    signIn: "Sign In",
    getStarted: "Get Started",
    // Homepage
    heroTitle: "Connect Creators with Brands",
    heroTitleHighlight: "Through Views",
    heroDescription: "The EU marketplace where brands post offers, creators deliver content, and payments flow securely through escrow after verified view counts.",
    startCreatingDeals: "Start Creating Deals",
    secureEscrow: "Secure Escrow",
    dayVerification: "14-Day Verification",
    whyChoose: "Why Choose ViewDeal?",
    whyChooseDescription: "Built for the creator economy with trust and transparency at its core",
    fairPricing: "Fair Pricing",
    fairPricingDesc: "Set your own rates like €1 per 1,000 views. Transparent and flexible.",
    secureEscrowTitle: "Secure Escrow",
    secureEscrowDesc: "Funds held safely until verified proof of views is delivered.",
    viewVerification: "View Verification",
    viewVerificationDesc: "14-day verification period ensures authentic engagement.",
    quickMatching: "Quick Matching",
    quickMatchingDesc: "Find the perfect creators or brands in minutes, not days.",
    howItWorks: "How It Works",
    howItWorksDescription: "Five simple steps from offer to payment",
    step1Title: "Create Your Profile",
    step1Desc: "Sign up as a creator or business",
    step2Title: "Browse or Post Offers",
    step2Desc: "Find deals or create campaigns",
    step3Title: "Secure Payment",
    step3Desc: "Funds held in escrow for safety",
    step4Title: "Deliver Content",
    step4Desc: "Creators post and submit proof",
    step5Title: "Get Paid",
    step5Desc: "Payment released after verification",
    readyToStart: "Ready to Get Started?",
    readyToStartDesc: "Join thousands of creators and brands building authentic partnerships through ViewDeal",
    createYourAccount: "Create Your Account",
    forCreators: "For Creators",
    forBrands: "For Brands",
    postAnOffer: "Post an Offer",
    manageCampaigns: "Manage Campaigns",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    footerText: "© 2025 ViewDeal. EU-based marketplace for creators and brands.",
    // Dashboard
    creatorDashboard: "Creator Dashboard",
    activeDeals: "Active Deals",
    totalEarnings: "Total Earnings",
    pendingPayment: "Pending Payment",
    totalViews: "Total Views",
    myApplications: "My Applications",
    submissions: "Submissions",
    accepted: "Accepted",
    pendingReview: "Pending Review",
    proofSubmitted: "Proof Submitted",
    verifying: "Verifying",
    completed: "Completed",
    openChat: "Open Chat",
    submitProof: "Submit Proof",
    submitProofTitle: "Submit Proof of Performance",
    contentURL: "Content URL",
    screenshotUpload: "Screenshot Upload",
    viewCount: "View Count",
    awaitingReview: "Awaiting Review",
    viewSubmission: "View Submission",
    submitted: "Submitted",
    proofURL: "Proof URL",
    viewContent: "View Content",
    awaitingVerification: "Awaiting verification. Payment will be released once approved.",
    // Offer Detail
    backToOffers: "Back to Offers",
    offerNotFound: "Offer Not Found",
    escrowFunded: "Escrow Funded",
    aboutThisOffer: "About This Offer",
    requirements: "Requirements",
    reward: "Reward",
    requiredViews: "Required Views",
    timeframe: "Timeframe",
    platform: "Platform",
    applications: "Applications",
    applyNow: "Apply Now",
    howItWorksTitle: "How It Works",
    applyToOffer: "Apply to this offer",
    waitForApproval: "Wait for business approval",
    createAndPost: "Create and post content",
    submitProofAfter: "Submit proof after 14 days",
    getPaidFromEscrow: "Get paid from escrow",
    applicationSubmitted: "Application Submitted!",
    businessWillReview: "The business will review your application soon.",
    // Offers
    findPerfectDeals: "Find Your Perfect Collaboration Deals",
    findPerfectDealsDesc: "Browse opportunities from top EU brands. Apply, create content, and get paid through secure escrow.",
    searchOffers: "Search offers...",
    views: "views",
    funded: "Funded",
    viewDetailsApply: "View Details & Apply",
    noOffersFound: "No offers found matching your search.",
    clearSearch: "Clear Search",
    // NotFound
    pageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",
    // Auth
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to continue to ViewDeal",
    createAccount: "Create Account",
    joinViewDeal: "Join ViewDeal and start collaborating",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    accountType: "Account Type",
    creator: "Creator",
    business: "Business",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    loginSuccess: "Login successful!",
    accountCreated: "Account created successfully!",
    // Create Offer
    createNewOffer: "Create New Offer",
    backToDashboard: "Back to Dashboard",
    offerTitle: "Offer Title",
    offerTitlePlaceholder: "e.g., Product Review, Unboxing Video...",
    description: "Description",
    descriptionPlaceholder: "Describe what you're looking for...",
    category: "Category",
    selectCategory: "Select a category",
    fitness: "Fitness",
    technology: "Technology",
    fashion: "Fashion",
    lifestyle: "Lifestyle",
    gaming: "Gaming",
    food: "Food & Drink",
    requiredViewsLabel: "Required Views",
    platformLabel: "Platform",
    selectPlatform: "Select platform",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Reward Type",
    selectRewardType: "Select reward type",
    cashPerView: "Cash per View/Video",
    discount: "Discount Code",
    freeGift: "Free Gift",
    cashAmount: "Cash Amount (€)",
    discountCode: "Discount Code",
    discountValue: "Discount Value (%)",
    giftDescription: "Gift Description",
    publishOffer: "Publish Offer",
    offerCreated: "Offer created successfully!",
    // Onboarding
    chooseYourPath: "Choose Your Path",
    areYouCreator: "Are you a creator looking for brand deals, or a business seeking influencers?",
    creatorTitle: "I'm a Creator",
    creatorDesc: "Get paid to create content for brands you love",
    creatorFeature1: "Browse paid collaboration offers",
    creatorFeature2: "Secure payments through escrow",
    creatorFeature3: "Build your portfolio",
    continueAsCreator: "Continue as Creator",
    businessTitle: "I'm a Business",
    businessDesc: "Find authentic creators to promote your brand",
    businessFeature1: "Post collaboration opportunities",
    businessFeature2: "Access verified creators",
    businessFeature3: "Track campaign performance",
    continueAsBusiness: "Continue as Business",
    alreadyHaveAccount: "Already have an account?",
    // Support
    supportTitle: "How Can We Help?",
    supportDescription: "Get in touch with our team or browse common questions",
    getInTouch: "Get in Touch",
    whatsappSupport: "WhatsApp Support",
    chatWithUs: "Chat with us directly",
    emailSupport: "Email Support",
    sendEmail: "Send us an email",
    frequentlyAsked: "Frequently Asked Questions",
    stillNeedHelp: "Still Need Help?",
    contactSupport: "Contact Support",
    chatNotFound: "Chat Not Found",
    active: "Active",
    typeMessage: "Type your message...",
    accessDenied: "Access Denied",
    onlyBusinessCanPost: "Only business accounts can create offers.",
    offerPostedSuccess: "Your offer has been posted successfully.",
    postOfferDescription: "Post an offer for creators to apply and promote your business",
    cashAmountDesc: "Creators will be paid based on verified views after 14 days",
    discountDetails: "Discount Details",
    discountPlaceholder: "E.g., 20% off all products, code: CREATOR20",
    giftPlaceholder: "Describe the free product or gift...",
    creatorFeature4: "Works with TikTok, Instagram & YouTube",
    businessFeature4: "Verify results before payment release",
    emailUs: "Email Us",
    chatOnWhatsApp: "Chat on WhatsApp",
    supportAvailability: "Our support team is available Monday to Friday, 9 AM - 6 PM CET",
    sendEmailButton: "Send Email",
  },
  it: {
    // Navbar
    browseOffers: "Sfoglia Offerte",
    dashboard: "Pannello",
    postOffer: "Pubblica Offerta",
    support: "Supporto",
    signIn: "Accedi",
    getStarted: "Inizia",
    // Homepage
    heroTitle: "Connetti Creatori con Brand",
    heroTitleHighlight: "Attraverso le Visualizzazioni",
    heroDescription: "Il marketplace europeo dove i brand pubblicano offerte, i creatori forniscono contenuti e i pagamenti fluiscono in sicurezza attraverso l'escrow dopo conteggi di visualizzazioni verificati.",
    startCreatingDeals: "Inizia a Creare Accordi",
    secureEscrow: "Escrow Sicuro",
    dayVerification: "Verifica 14 Giorni",
    whyChoose: "Perché Scegliere ViewDeal?",
    whyChooseDescription: "Costruito per l'economia dei creator con fiducia e trasparenza al centro",
    fairPricing: "Prezzi Equi",
    fairPricingDesc: "Imposta le tue tariffe come €1 per 1.000 visualizzazioni. Trasparente e flessibile.",
    secureEscrowTitle: "Escrow Sicuro",
    secureEscrowDesc: "Fondi conservati in sicurezza fino alla consegna della prova verificata delle visualizzazioni.",
    viewVerification: "Verifica Visualizzazioni",
    viewVerificationDesc: "Il periodo di verifica di 14 giorni garantisce un coinvolgimento autentico.",
    quickMatching: "Abbinamento Rapido",
    quickMatchingDesc: "Trova i creator o brand perfetti in minuti, non giorni.",
    howItWorks: "Come Funziona",
    howItWorksDescription: "Cinque semplici passaggi dall'offerta al pagamento",
    step1Title: "Crea il Tuo Profilo",
    step1Desc: "Registrati come creator o azienda",
    step2Title: "Sfoglia o Pubblica Offerte",
    step2Desc: "Trova accordi o crea campagne",
    step3Title: "Pagamento Sicuro",
    step3Desc: "Fondi trattenuti in escrow per sicurezza",
    step4Title: "Fornisci Contenuto",
    step4Desc: "I creator pubblicano e inviano la prova",
    step5Title: "Ricevi il Pagamento",
    step5Desc: "Pagamento rilasciato dopo la verifica",
    readyToStart: "Pronto per Iniziare?",
    readyToStartDesc: "Unisciti a migliaia di creator e brand che costruiscono partnership autentiche attraverso ViewDeal",
    createYourAccount: "Crea il Tuo Account",
    forCreators: "Per i Creator",
    forBrands: "Per i Brand",
    postAnOffer: "Pubblica un'Offerta",
    manageCampaigns: "Gestisci Campagne",
    helpCenter: "Centro Assistenza",
    contactUs: "Contattaci",
    footerText: "© 2025 ViewDeal. Marketplace europeo per creator e brand.",
    // Dashboard
    creatorDashboard: "Pannello Creator",
    activeDeals: "Accordi Attivi",
    totalEarnings: "Guadagni Totali",
    pendingPayment: "Pagamento in Attesa",
    totalViews: "Visualizzazioni Totali",
    myApplications: "Le Mie Candidature",
    submissions: "Invii",
    accepted: "Accettato",
    pendingReview: "In Attesa di Revisione",
    proofSubmitted: "Prova Inviata",
    verifying: "Verifica in Corso",
    completed: "Completato",
    openChat: "Apri Chat",
    submitProof: "Invia Prova",
    submitProofTitle: "Invia Prova di Prestazione",
    contentURL: "URL del Contenuto",
    screenshotUpload: "Carica Screenshot",
    viewCount: "Conteggio Visualizzazioni",
    awaitingReview: "In Attesa di Revisione",
    viewSubmission: "Visualizza Invio",
    submitted: "Inviato",
    proofURL: "URL Prova",
    viewContent: "Visualizza Contenuto",
    awaitingVerification: "In attesa di verifica. Il pagamento sarà rilasciato una volta approvato.",
    // Offer Detail
    backToOffers: "Torna alle Offerte",
    offerNotFound: "Offerta Non Trovata",
    escrowFunded: "Finanziato Escrow",
    aboutThisOffer: "Su Questa Offerta",
    requirements: "Requisiti",
    reward: "Ricompensa",
    requiredViews: "Visualizzazioni Richieste",
    timeframe: "Tempistiche",
    platform: "Piattaforma",
    applications: "Candidature",
    applyNow: "Candidati Ora",
    howItWorksTitle: "Come Funziona",
    applyToOffer: "Candidati a questa offerta",
    waitForApproval: "Attendi l'approvazione dell'azienda",
    createAndPost: "Crea e pubblica contenuto",
    submitProofAfter: "Invia la prova dopo 14 giorni",
    getPaidFromEscrow: "Ricevi il pagamento dall'escrow",
    applicationSubmitted: "Candidatura Inviata!",
    businessWillReview: "L'azienda esaminerà presto la tua candidatura.",
    // Offers
    findPerfectDeals: "Trova le Tue Collaborazioni Perfette",
    findPerfectDealsDesc: "Sfoglia le opportunità dai migliori brand europei. Candidati, crea contenuti e ricevi pagamenti tramite escrow sicuro.",
    searchOffers: "Cerca offerte...",
    views: "visualizzazioni",
    funded: "Finanziato",
    viewDetailsApply: "Vedi Dettagli e Candidati",
    noOffersFound: "Nessuna offerta trovata corrispondente alla tua ricerca.",
    clearSearch: "Cancella Ricerca",
    // NotFound
    pageNotFound: "Ops! Pagina non trovata",
    returnToHome: "Torna alla Home",
    // Auth
    welcomeBack: "Bentornato",
    signInToContinue: "Accedi per continuare su ViewDeal",
    createAccount: "Crea Account",
    joinViewDeal: "Unisciti a ViewDeal e inizia a collaborare",
    email: "Email",
    password: "Password",
    confirmPassword: "Conferma Password",
    accountType: "Tipo di Account",
    creator: "Creator",
    business: "Azienda",
    loggingIn: "Accesso in corso...",
    creatingAccount: "Creazione account...",
    loginSuccess: "Accesso riuscito!",
    accountCreated: "Account creato con successo!",
    // Create Offer
    createNewOffer: "Crea Nuova Offerta",
    backToDashboard: "Torna al Pannello",
    offerTitle: "Titolo Offerta",
    offerTitlePlaceholder: "es., Recensione Prodotto, Video Unboxing...",
    description: "Descrizione",
    descriptionPlaceholder: "Descrivi cosa stai cercando...",
    category: "Categoria",
    selectCategory: "Seleziona una categoria",
    fitness: "Fitness",
    technology: "Tecnologia",
    fashion: "Moda",
    lifestyle: "Stile di Vita",
    gaming: "Gaming",
    food: "Cibo e Bevande",
    requiredViewsLabel: "Visualizzazioni Richieste",
    platformLabel: "Piattaforma",
    selectPlatform: "Seleziona piattaforma",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Tipo di Ricompensa",
    selectRewardType: "Seleziona tipo di ricompensa",
    cashPerView: "Denaro per Visualizzazione/Video",
    discount: "Codice Sconto",
    freeGift: "Regalo Gratuito",
    cashAmount: "Importo in Denaro (€)",
    discountCode: "Codice Sconto",
    discountValue: "Valore Sconto (%)",
    giftDescription: "Descrizione Regalo",
    publishOffer: "Pubblica Offerta",
    offerCreated: "Offerta creata con successo!",
    // Onboarding
    chooseYourPath: "Scegli il Tuo Percorso",
    areYouCreator: "Sei un creator in cerca di accordi con brand, o un'azienda in cerca di influencer?",
    creatorTitle: "Sono un Creator",
    creatorDesc: "Ricevi un compenso per creare contenuti per i brand che ami",
    creatorFeature1: "Sfoglia offerte di collaborazione pagate",
    creatorFeature2: "Pagamenti sicuri tramite escrow",
    creatorFeature3: "Costruisci il tuo portfolio",
    continueAsCreator: "Continua come Creator",
    businessTitle: "Sono un'Azienda",
    businessDesc: "Trova creator autentici per promuovere il tuo brand",
    businessFeature1: "Pubblica opportunità di collaborazione",
    businessFeature2: "Accedi a creator verificati",
    businessFeature3: "Monitora le prestazioni delle campagne",
    continueAsBusiness: "Continua come Azienda",
    alreadyHaveAccount: "Hai già un account?",
    // Support
    supportTitle: "Come Possiamo Aiutarti?",
    supportDescription: "Contatta il nostro team o sfoglia le domande comuni",
    getInTouch: "Mettiti in Contatto",
    whatsappSupport: "Supporto WhatsApp",
    chatWithUs: "Chatta direttamente con noi",
    emailSupport: "Supporto Email",
    sendEmail: "Inviaci un'email",
    frequentlyAsked: "Domande Frequenti",
    stillNeedHelp: "Hai Ancora Bisogno di Aiuto?",
    contactSupport: "Contatta il Supporto",
    chatNotFound: "Chat Non Trovata",
    active: "Attivo",
    typeMessage: "Scrivi il tuo messaggio...",
    accessDenied: "Accesso Negato",
    onlyBusinessCanPost: "Solo gli account aziendali possono creare offerte.",
    offerPostedSuccess: "La tua offerta è stata pubblicata con successo.",
    postOfferDescription: "Pubblica un'offerta per i creator per candidarsi e promuovere la tua azienda",
    cashAmountDesc: "I creator verranno pagati in base alle visualizzazioni verificate dopo 14 giorni",
    discountDetails: "Dettagli Sconto",
    discountPlaceholder: "Es., 20% di sconto su tutti i prodotti, codice: CREATOR20",
    giftPlaceholder: "Descrivi il prodotto o regalo gratuito...",
    creatorFeature4: "Funziona con TikTok, Instagram e YouTube",
    businessFeature4: "Verifica i risultati prima del rilascio del pagamento",
    emailUs: "Inviaci un'Email",
    chatOnWhatsApp: "Chatta su WhatsApp",
    supportAvailability: "Il nostro team di supporto è disponibile dal lunedì al venerdì, 9:00 - 18:00 CET",
    sendEmailButton: "Invia Email",
  },
  es: {
    // Navbar
    browseOffers: "Ver Ofertas",
    dashboard: "Panel",
    postOffer: "Publicar Oferta",
    support: "Soporte",
    signIn: "Iniciar Sesión",
    getStarted: "Comenzar",
    // Homepage
    heroTitle: "Conecta Creadores con Marcas",
    heroTitleHighlight: "A Través de Vistas",
    heroDescription: "El marketplace de la UE donde las marcas publican ofertas, los creadores entregan contenido y los pagos fluyen de forma segura a través del depósito en garantía después de recuentos de vistas verificados.",
    startCreatingDeals: "Comienza a Crear Acuerdos",
    secureEscrow: "Depósito Seguro",
    dayVerification: "Verificación de 14 Días",
    whyChoose: "¿Por Qué Elegir ViewDeal?",
    whyChooseDescription: "Construido para la economía de creadores con confianza y transparencia en su núcleo",
    fairPricing: "Precios Justos",
    fairPricingDesc: "Establece tus propias tarifas como €1 por 1,000 vistas. Transparente y flexible.",
    secureEscrowTitle: "Depósito Seguro",
    secureEscrowDesc: "Fondos retenidos de forma segura hasta que se entregue la prueba verificada de vistas.",
    viewVerification: "Verificación de Vistas",
    viewVerificationDesc: "El período de verificación de 14 días garantiza un compromiso auténtico.",
    quickMatching: "Emparejamiento Rápido",
    quickMatchingDesc: "Encuentra los creadores o marcas perfectas en minutos, no días.",
    howItWorks: "Cómo Funciona",
    howItWorksDescription: "Cinco pasos simples desde la oferta hasta el pago",
    step1Title: "Crea Tu Perfil",
    step1Desc: "Regístrate como creador o empresa",
    step2Title: "Explora o Publica Ofertas",
    step2Desc: "Encuentra acuerdos o crea campañas",
    step3Title: "Pago Seguro",
    step3Desc: "Fondos retenidos en depósito por seguridad",
    step4Title: "Entrega Contenido",
    step4Desc: "Los creadores publican y envían pruebas",
    step5Title: "Recibe el Pago",
    step5Desc: "Pago liberado después de la verificación",
    readyToStart: "¿Listo para Comenzar?",
    readyToStartDesc: "Únete a miles de creadores y marcas construyendo asociaciones auténticas a través de ViewDeal",
    createYourAccount: "Crea Tu Cuenta",
    forCreators: "Para Creadores",
    forBrands: "Para Marcas",
    postAnOffer: "Publicar una Oferta",
    manageCampaigns: "Gestionar Campañas",
    helpCenter: "Centro de Ayuda",
    contactUs: "Contáctanos",
    footerText: "© 2025 ViewDeal. Marketplace europeo para creadores y marcas.",
    // Dashboard
    creatorDashboard: "Panel de Creador",
    activeDeals: "Acuerdos Activos",
    totalEarnings: "Ganancias Totales",
    pendingPayment: "Pago Pendiente",
    totalViews: "Vistas Totales",
    myApplications: "Mis Solicitudes",
    submissions: "Envíos",
    accepted: "Aceptado",
    pendingReview: "Revisión Pendiente",
    proofSubmitted: "Prueba Enviada",
    verifying: "Verificando",
    completed: "Completado",
    openChat: "Abrir Chat",
    submitProof: "Enviar Prueba",
    submitProofTitle: "Enviar Prueba de Rendimiento",
    contentURL: "URL del Contenido",
    screenshotUpload: "Subir Captura de Pantalla",
    viewCount: "Conteo de Vistas",
    awaitingReview: "En Espera de Revisión",
    viewSubmission: "Ver Envío",
    submitted: "Enviado",
    proofURL: "URL de Prueba",
    viewContent: "Ver Contenido",
    awaitingVerification: "Esperando verificación. El pago se liberará una vez aprobado.",
    // Offer Detail
    backToOffers: "Volver a Ofertas",
    offerNotFound: "Oferta No Encontrada",
    escrowFunded: "Financiado en Depósito",
    aboutThisOffer: "Acerca de Esta Oferta",
    requirements: "Requisitos",
    reward: "Recompensa",
    requiredViews: "Vistas Requeridas",
    timeframe: "Plazo",
    platform: "Plataforma",
    applications: "Solicitudes",
    applyNow: "Aplicar Ahora",
    howItWorksTitle: "Cómo Funciona",
    applyToOffer: "Aplicar a esta oferta",
    waitForApproval: "Esperar la aprobación de la empresa",
    createAndPost: "Crear y publicar contenido",
    submitProofAfter: "Enviar prueba después de 14 días",
    getPaidFromEscrow: "Recibir pago del depósito",
    applicationSubmitted: "¡Solicitud Enviada!",
    businessWillReview: "La empresa revisará tu solicitud pronto.",
    // Offers
    findPerfectDeals: "Encuentra Tus Acuerdos de Colaboración Perfectos",
    findPerfectDealsDesc: "Explora oportunidades de las mejores marcas de la UE. Aplica, crea contenido y recibe pagos a través de depósito seguro.",
    searchOffers: "Buscar ofertas...",
    views: "vistas",
    funded: "Financiado",
    viewDetailsApply: "Ver Detalles y Aplicar",
    noOffersFound: "No se encontraron ofertas que coincidan con tu búsqueda.",
    clearSearch: "Limpiar Búsqueda",
    // NotFound
    pageNotFound: "¡Ups! Página no encontrada",
    returnToHome: "Volver al Inicio",
    // Auth
    welcomeBack: "Bienvenido de Nuevo",
    signInToContinue: "Inicia sesión para continuar en ViewDeal",
    createAccount: "Crear Cuenta",
    joinViewDeal: "Únete a ViewDeal y comienza a colaborar",
    email: "Correo Electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    accountType: "Tipo de Cuenta",
    creator: "Creador",
    business: "Empresa",
    loggingIn: "Iniciando sesión...",
    creatingAccount: "Creando cuenta...",
    loginSuccess: "¡Inicio de sesión exitoso!",
    accountCreated: "¡Cuenta creada con éxito!",
    // Create Offer
    createNewOffer: "Crear Nueva Oferta",
    backToDashboard: "Volver al Panel",
    offerTitle: "Título de la Oferta",
    offerTitlePlaceholder: "ej., Reseña de Producto, Video Unboxing...",
    description: "Descripción",
    descriptionPlaceholder: "Describe lo que estás buscando...",
    category: "Categoría",
    selectCategory: "Seleccionar una categoría",
    fitness: "Fitness",
    technology: "Tecnología",
    fashion: "Moda",
    lifestyle: "Estilo de Vida",
    gaming: "Gaming",
    food: "Comida y Bebida",
    requiredViewsLabel: "Vistas Requeridas",
    platformLabel: "Plataforma",
    selectPlatform: "Seleccionar plataforma",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Tipo de Recompensa",
    selectRewardType: "Seleccionar tipo de recompensa",
    cashPerView: "Dinero por Vista/Video",
    discount: "Código de Descuento",
    freeGift: "Regalo Gratis",
    cashAmount: "Cantidad en Efectivo (€)",
    discountCode: "Código de Descuento",
    discountValue: "Valor del Descuento (%)",
    giftDescription: "Descripción del Regalo",
    publishOffer: "Publicar Oferta",
    offerCreated: "¡Oferta creada con éxito!",
    // Onboarding
    chooseYourPath: "Elige Tu Camino",
    areYouCreator: "¿Eres un creador buscando acuerdos con marcas, o una empresa buscando influencers?",
    creatorTitle: "Soy un Creador",
    creatorDesc: "Recibe pago por crear contenido para marcas que amas",
    creatorFeature1: "Explora ofertas de colaboración pagadas",
    creatorFeature2: "Pagos seguros a través de depósito",
    creatorFeature3: "Construye tu portafolio",
    continueAsCreator: "Continuar como Creador",
    businessTitle: "Soy una Empresa",
    businessDesc: "Encuentra creadores auténticos para promocionar tu marca",
    businessFeature1: "Publicar oportunidades de colaboración",
    businessFeature2: "Acceder a creadores verificados",
    businessFeature3: "Rastrear rendimiento de campañas",
    continueAsBusiness: "Continuar como Empresa",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    // Support
    supportTitle: "¿Cómo Podemos Ayudarte?",
    supportDescription: "Ponte en contacto con nuestro equipo o explora preguntas comunes",
    getInTouch: "Ponte en Contacto",
    whatsappSupport: "Soporte WhatsApp",
    chatWithUs: "Chatea directamente con nosotros",
    emailSupport: "Soporte por Correo",
    sendEmail: "Envíanos un correo",
    frequentlyAsked: "Preguntas Frecuentes",
    stillNeedHelp: "¿Aún Necesitas Ayuda?",
    contactSupport: "Contactar Soporte",
    chatNotFound: "Chat No Encontrado",
    active: "Activo",
    typeMessage: "Escribe tu mensaje...",
    accessDenied: "Acceso Denegado",
    onlyBusinessCanPost: "Solo las cuentas empresariales pueden crear ofertas.",
    offerPostedSuccess: "Tu oferta se ha publicado con éxito.",
    postOfferDescription: "Publica una oferta para que los creadores se postulen y promocionen tu negocio",
    cashAmountDesc: "Los creadores recibirán el pago según las vistas verificadas después de 14 días",
    discountDetails: "Detalles del Descuento",
    discountPlaceholder: "Ej., 20% de descuento en todos los productos, código: CREATOR20",
    giftPlaceholder: "Describe el producto o regalo gratuito...",
    creatorFeature4: "Funciona con TikTok, Instagram y YouTube",
    businessFeature4: "Verifica los resultados antes de liberar el pago",
    emailUs: "Envíanos un Email",
    chatOnWhatsApp: "Chatea en WhatsApp",
    supportAvailability: "Nuestro equipo de soporte está disponible de lunes a viernes, 9 AM - 6 PM CET",
    sendEmailButton: "Enviar Email",
  },
};

const detectUserLanguage = (): Language => {
  const stored = localStorage.getItem("userLanguage");
  if (stored && (stored === "en" || stored === "it" || stored === "es")) {
    return stored as Language;
  }

  const browserLang = navigator.language.toLowerCase();
  if (browserLang.startsWith("it")) return "it";
  if (browserLang.startsWith("es")) return "es";
  return "en";
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(detectUserLanguage);

  useEffect(() => {
    localStorage.setItem("userLanguage", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
