import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "it" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    browseOffers: "Browse Offers",
    dashboard: "Dashboard",
    postOffer: "Post Offer",
    support: "Support",
    signIn: "Sign In",
    getStarted: "Get Started",
    // Homepage
    heroTitle: "Connect Creators with Brands",
    heroTitleHighlight: "Through Views",
    heroDescription: "The EU marketplace where brands post offers, creators deliver content, and payments flow securely through escrow after verified view counts.",
    startCreatingDeals: "Start Creating Deals",
    secureEscrow: "Secure Escrow",
    dayVerification: "14-Day Verification",
    whyChoose: "Why Choose weasydeal?",
    whyChooseDescription: "Built for the creator economy with trust and transparency at its core",
    fairPricing: "Fair Pricing",
    fairPricingDesc: "Set your own rates like €1 per 1,000 views. Transparent and flexible.",
    secureEscrowTitle: "Secure Escrow",
    secureEscrowDesc: "Funds held safely until verified proof of views is delivered.",
    viewVerification: "View Verification",
    viewVerificationDesc: "14-day verification period ensures authentic engagement.",
    quickMatching: "Quick Matching",
    quickMatchingDesc: "Find the perfect creators or brands in minutes, not days.",
    howItWorks: "How It Works",
    howItWorksDescription: "Five simple steps from offer to payment",
    step1Title: "Create Your Profile",
    step1Desc: "Sign up as a creator or business",
    step2Title: "Browse or Post Offers",
    step2Desc: "Find deals or create campaigns",
    step3Title: "Secure Payment",
    step3Desc: "Funds held in escrow for safety",
    step4Title: "Deliver Content",
    step4Desc: "Creators post and submit proof",
    step5Title: "Get Paid",
    step5Desc: "Payment released after verification",
    readyToStart: "Ready to Get Started?",
    readyToStartDesc: "Join thousands of creators and brands building authentic partnerships through weasydeal",
    createYourAccount: "Create Your Account",
    forCreators: "For Creators",
    forBrands: "For Brands",
    postAnOffer: "Post an Offer",
    manageCampaigns: "Manage Campaigns",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    footerText: "© 2025 weasydeal. EU-based marketplace for creators and brands.",
    // Dashboard
    creatorDashboard: "Creator Dashboard",
    activeDeals: "Active Deals",
    totalEarnings: "Total Earnings",
    pendingPayment: "Pending Payment",
    totalViews: "Total Views",
    myApplications: "My Applications",
    submissions: "Submissions",
    accepted: "Accepted",
    pendingReview: "Pending Review",
    proofSubmitted: "Proof Submitted",
    verifying: "Verifying",
    completed: "Completed",
    openChat: "Open Chat",
    submitProof: "Submit Proof",
    submitProofTitle: "Submit Proof of Performance",
    contentURL: "Content URL",
    screenshotUpload: "Screenshot Upload",
    viewCount: "View Count",
    awaitingReview: "Awaiting Review",
    viewSubmission: "View Submission",
    submitted: "Submitted",
    proofURL: "Proof URL",
    viewContent: "View Content",
    awaitingVerification: "Awaiting verification. Payment will be released once approved.",
    // Offer Detail
    backToOffers: "Back to Offers",
    offerNotFound: "Offer Not Found",
    escrowFunded: "Escrow Funded",
    aboutThisOffer: "About This Offer",
    requirements: "Requirements",
    reward: "Reward",
    requiredViews: "Required Views",
    timeframe: "Timeframe",
    platform: "Platform",
    applications: "Applications",
    applyNow: "Apply Now",
    howItWorksTitle: "How It Works",
    applyToOffer: "Apply to this offer",
    waitForApproval: "Wait for business approval",
    createAndPost: "Create and post content",
    submitProofAfter: "Submit proof after 14 days",
    getPaidFromEscrow: "Get paid from escrow",
    applicationSubmitted: "Application Submitted!",
    businessWillReview: "The business will review your application soon.",
    // Offers
    findPerfectDeals: "Find Your Perfect Collaboration Deals",
    findPerfectDealsDesc: "Browse opportunities from top EU brands. Apply, create content, and get paid through secure escrow.",
    searchOffers: "Search offers...",
    views: "views",
    funded: "Funded",
    viewDetailsApply: "View Details & Apply",
    noOffersFound: "No offers found matching your search.",
    clearSearch: "Clear Search",
    // NotFound
    pageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",
    // Auth
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to continue to weasydeal",
    createAccount: "Create Account",
    joinViewDeal: "Join weasydeal and start collaborating",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    accountType: "Account Type",
    creator: "Creator",
    business: "Business",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    loginSuccess: "Login successful!",
    accountCreated: "Account created successfully!",
    // Create Offer
    createNewOffer: "Create New Offer",
    backToDashboard: "Back to Dashboard",
    offerTitle: "Offer Title",
    offerTitlePlaceholder: "e.g., Product Review, Unboxing Video...",
    description: "Description",
    descriptionPlaceholder: "Describe what you're looking for...",
    category: "Category",
    selectCategory: "Select a category",
    fitness: "Fitness",
    technology: "Technology",
    fashion: "Fashion",
    lifestyle: "Lifestyle",
    gaming: "Gaming",
    food: "Food & Drink",
    requiredViewsLabel: "Required Views",
    platformLabel: "Platform",
    selectPlatform: "Select platform",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Reward Type",
    selectRewardType: "Select reward type",
    cashPerView: "Cash per View/Video",
    discount: "Discount Code",
    freeGift: "Free Gift",
    cashAmount: "Cash Amount (€)",
    discountCode: "Discount Code",
    discountValue: "Discount Value (%)",
    giftDescription: "Gift Description",
    publishOffer: "Publish Offer",
    offerCreated: "Offer created successfully!",
    // Onboarding
    chooseYourPath: "Choose Your Path",
    areYouCreator: "Are you a creator looking for brand deals, or a business seeking influencers?",
    creatorTitle: "I'm a Creator",
    creatorDesc: "Get paid to create content for brands you love",
    creatorFeature1: "Browse paid collaboration offers",
    creatorFeature2: "Secure payments through escrow",
    creatorFeature3: "Build your portfolio",
    continueAsCreator: "Continue as Creator",
    businessTitle: "I'm a Business",
    businessDesc: "Find authentic creators to promote your brand",
    businessFeature1: "Post collaboration opportunities",
    businessFeature2: "Access verified creators",
    businessFeature3: "Track campaign performance",
    continueAsBusiness: "Continue as Business",
    alreadyHaveAccount: "Already have an account?",
    // Support
    supportTitle: "How Can We Help?",
    supportDescription: "Get in touch with our team or browse common questions",
    getInTouch: "Get in Touch",
    whatsappSupport: "WhatsApp Support",
    chatWithUs: "Chat with us directly",
    emailSupport: "Email Support",
    sendEmail: "Send us an email",
    frequentlyAsked: "Frequently Asked Questions",
    stillNeedHelp: "Still Need Help?",
    contactSupport: "Contact Support",
    chatNotFound: "Chat Not Found",
    active: "Active",
    typeMessage: "Type your message...",
    accessDenied: "Access Denied",
    onlyBusinessCanPost: "Only business accounts can create offers.",
    offerPostedSuccess: "Your offer has been posted successfully.",
    postOfferDescription: "Post an offer for creators to apply and promote your business",
    cashAmountDesc: "Creators will be paid based on verified views after 14 days",
    discountDetails: "Discount Details",
    discountPlaceholder: "E.g., 20% off all products, code: CREATOR20",
    giftPlaceholder: "Describe the free product or gift...",
    creatorFeature4: "Works with TikTok, Instagram & YouTube",
    businessFeature4: "Verify results before payment release",
    emailUs: "Email Us",
    chatOnWhatsApp: "Chat on WhatsApp",
    supportAvailability: "Our support team is available Monday to Friday, 9 AM - 6 PM CET",
    sendEmailButton: "Send Email",
    totalRewardAmount: "Total Reward Amount (€)",
    totalRewardDesc: "Total amount to be paid if creator achieves 100% or more of required views. Creators earn proportionally based on views achieved (e.g., 50% of views = 50% of reward, capped at 100%)",
    calculatedEarnings: "Calculated Earnings",
    ofTarget: "of target",
    actualViews: "actual views",
    freeGiftDetails: "Free Gift Details",
    totalReward: "Total Reward",
    learnHowItWorks: "Learn How It Works",
    seeFullProcess: "See the Full Process",
    // How It Works page
    transparentMarketplace: "Transparent Marketplace",
    howItWorksHero: "Your Journey From Discovery to Payment",
    howItWorksSubtitle: "A transparent, secure platform where creators and businesses build authentic partnerships backed by verified performance.",
    whyViewDealWorks: "Why weasydeal Works",
    whyViewDealWorksDesc: "Built on trust, transparency, and fair compensation for all parties.",
    secureEscrowFeature: "All funds are held in secure escrow until content is verified, protecting both creators and businesses.",
    percentageBasedTitle: "Percentage-Based Rewards",
    percentageBasedFeature: "Earn based on actual performance. Hit 50% of views, earn 50% of reward. Exceed targets, earn the full reward.",
    instantMatchingTitle: "Instant Matching",
    instantMatchingFeature: "Connect with the right creators or brands in minutes through our smart matching system.",
    verifiedPaymentsTitle: "Verified Payments",
    verifiedPaymentsFeature: "14-day verification period ensures authentic engagement before payment release.",
    creatorJourneyTitle: "Your Creator Journey",
    creatorJourneyDesc: "From discovering opportunities to getting paid - here's how creators succeed on weasydeal.",
    step: "Step",
    creatorStep1Title: "Create Your Profile",
    creatorStep1Desc: "Sign up in minutes and showcase your content portfolio, audience demographics, and engagement rates.",
    creatorStep2Title: "Browse & Apply to Offers",
    creatorStep2Desc: "Explore verified brand collaborations that match your niche, audience size, and content style.",
    creatorStep3Title: "Get Approved",
    creatorStep3Desc: "Brands review your application and approve creators who align with their campaign goals.",
    creatorStep4Title: "Create & Submit Content",
    creatorStep4Desc: "Produce authentic content following brand guidelines. Post on your platform and submit proof with view counts.",
    creatorStep5Title: "Earn Your Reward",
    creatorStep5Desc: "After 14-day verification, earn based on actual views achieved. Funds released automatically from escrow.",
    startAsCreator: "Start as a Creator",
    businessJourneyTitle: "Your Business Journey",
    businessJourneyDesc: "Launch campaigns, find authentic creators, and pay only for verified results.",
    businessStep1Title: "Post Your Campaign",
    businessStep1Desc: "Define your offer, set view targets, total reward amount, and specify creator requirements.",
    businessStep2Title: "Review Applications",
    businessStep2Desc: "Creators apply to your campaign. Review their profiles, past work, and engagement metrics.",
    businessStep3Title: "Approve Creators",
    businessStep3Desc: "Select the best-fit creators for your brand. Fund escrow to secure the collaboration.",
    businessStep4Title: "Track Performance",
    businessStep4Desc: "Monitor content submissions and view counts in real-time through your dashboard.",
    businessStep5Title: "Verified Results",
    businessStep5Desc: "After 14-day verification, payment is released based on actual views achieved. Full transparency guaranteed.",
    startAsBusiness: "Start as a Business",
    trustSecurityTitle: "Trust & Security Built In",
    trustSecurityDesc: "weasydeal protects both creators and businesses with industry-leading security measures and transparent processes.",
    escrowProtection: "100% escrow protection for all deals",
    verifiedMetrics: "Verified view counts and engagement metrics",
    disputeResolution: "Fair dispute resolution process",
    transparentPayments: "Transparent payment calculations",
    daysVerification: "Days Verification",
    escrowProtected: "Escrow Protected",
    activeUsers: "Active Users",
    paidOut: "Paid Out",
    readyToTransform: "Ready to Transform Your Collaborations?",
    readyToTransformDesc: "Join the marketplace where creators and brands connect through authentic partnerships and verified results.",
    joinNow: "Join Now - It's Free",
    faqQuestion1: "How does the escrow payment system work?",
    faqAnswer1: "When a brand accepts your application, they fund the escrow. The payment is held securely until you submit proof of views and it's verified after 14 days.",
    faqQuestion2: "What proof do I need to submit?",
    faqAnswer2: "You need to submit a screenshot of your view count and the URL of your content. The view count must be checked 14 days after posting.",
    faqQuestion3: "Which platforms are supported?",
    faqAnswer3: "Currently, weasydeal supports TikTok, Instagram, and YouTube for view verification.",
    faqQuestion4: "What if I don't reach the required views?",
    faqAnswer4: "If the view count doesn't meet the requirement after 14 days, the brand can choose to release partial payment or return the escrow amount.",
    faqQuestion5: "Is weasydeal available outside the EU?",
    faqAnswer5: "Currently, weasydeal operates exclusively within the European Union to ensure compliance with EU regulations.",
  },
  it: {
    // Navbar
    browseOffers: "Sfoglia Offerte",
    dashboard: "Pannello",
    postOffer: "Pubblica Offerta",
    support: "Supporto",
    signIn: "Accedi",
    getStarted: "Inizia",
    // Homepage
    heroTitle: "Connetti Creatori con Brand",
    heroTitleHighlight: "Attraverso le Visualizzazioni",
    heroDescription: "Il marketplace europeo dove i brand pubblicano offerte, i creatori forniscono contenuti e i pagamenti fluiscono in sicurezza attraverso l'escrow dopo conteggi di visualizzazioni verificati.",
    startCreatingDeals: "Inizia a Creare Accordi",
    secureEscrow: "Escrow Sicuro",
    dayVerification: "Verifica 14 Giorni",
    whyChoose: "Perché Scegliere weasydeal?",
    whyChooseDescription: "Costruito per l'economia dei creator con fiducia e trasparenza al centro",
    fairPricing: "Prezzi Equi",
    fairPricingDesc: "Imposta le tue tariffe come €1 per 1.000 visualizzazioni. Trasparente e flessibile.",
    secureEscrowTitle: "Escrow Sicuro",
    secureEscrowDesc: "Fondi conservati in sicurezza fino alla consegna della prova verificata delle visualizzazioni.",
    viewVerification: "Verifica Visualizzazioni",
    viewVerificationDesc: "Il periodo di verifica di 14 giorni garantisce un coinvolgimento autentico.",
    quickMatching: "Abbinamento Rapido",
    quickMatchingDesc: "Trova i creator o brand perfetti in minuti, non giorni.",
    howItWorks: "Come Funziona",
    howItWorksDescription: "Cinque semplici passaggi dall'offerta al pagamento",
    step1Title: "Crea il Tuo Profilo",
    step1Desc: "Registrati come creator o azienda",
    step2Title: "Sfoglia o Pubblica Offerte",
    step2Desc: "Trova accordi o crea campagne",
    step3Title: "Pagamento Sicuro",
    step3Desc: "Fondi trattenuti in escrow per sicurezza",
    step4Title: "Fornisci Contenuto",
    step4Desc: "I creator pubblicano e inviano la prova",
    step5Title: "Ricevi il Pagamento",
    step5Desc: "Pagamento rilasciato dopo la verifica",
    readyToStart: "Pronto per Iniziare?",
    readyToStartDesc: "Unisciti a migliaia di creator e brand che costruiscono partnership autentiche attraverso weasydeal",
    createYourAccount: "Crea il Tuo Account",
    forCreators: "Per i Creator",
    forBrands: "Per i Brand",
    postAnOffer: "Pubblica un'Offerta",
    manageCampaigns: "Gestisci Campagne",
    helpCenter: "Centro Assistenza",
    contactUs: "Contattaci",
    footerText: "© 2025 weasydeal. Marketplace europeo per creator e brand.",
    // Dashboard
    creatorDashboard: "Pannello Creator",
    activeDeals: "Accordi Attivi",
    totalEarnings: "Guadagni Totali",
    pendingPayment: "Pagamento in Attesa",
    totalViews: "Visualizzazioni Totali",
    myApplications: "Le Mie Candidature",
    submissions: "Invii",
    accepted: "Accettato",
    pendingReview: "In Attesa di Revisione",
    proofSubmitted: "Prova Inviata",
    verifying: "Verifica in Corso",
    completed: "Completato",
    openChat: "Apri Chat",
    submitProof: "Invia Prova",
    submitProofTitle: "Invia Prova di Prestazione",
    contentURL: "URL del Contenuto",
    screenshotUpload: "Carica Screenshot",
    viewCount: "Conteggio Visualizzazioni",
    awaitingReview: "In Attesa di Revisione",
    viewSubmission: "Visualizza Invio",
    submitted: "Inviato",
    proofURL: "URL Prova",
    viewContent: "Visualizza Contenuto",
    awaitingVerification: "In attesa di verifica. Il pagamento sarà rilasciato una volta approvato.",
    // Offer Detail
    backToOffers: "Torna alle Offerte",
    offerNotFound: "Offerta Non Trovata",
    escrowFunded: "Finanziato Escrow",
    aboutThisOffer: "Su Questa Offerta",
    requirements: "Requisiti",
    reward: "Ricompensa",
    requiredViews: "Visualizzazioni Richieste",
    timeframe: "Tempistiche",
    platform: "Piattaforma",
    applications: "Candidature",
    applyNow: "Candidati Ora",
    howItWorksTitle: "Come Funziona",
    applyToOffer: "Candidati a questa offerta",
    waitForApproval: "Attendi l'approvazione dell'azienda",
    createAndPost: "Crea e pubblica contenuto",
    submitProofAfter: "Invia la prova dopo 14 giorni",
    getPaidFromEscrow: "Ricevi il pagamento dall'escrow",
    applicationSubmitted: "Candidatura Inviata!",
    businessWillReview: "L'azienda esaminerà presto la tua candidatura.",
    // Offers
    findPerfectDeals: "Trova le Tue Collaborazioni Perfette",
    findPerfectDealsDesc: "Sfoglia le opportunità dai migliori brand europei. Candidati, crea contenuti e ricevi pagamenti tramite escrow sicuro.",
    searchOffers: "Cerca offerte...",
    views: "visualizzazioni",
    funded: "Finanziato",
    viewDetailsApply: "Vedi Dettagli e Candidati",
    noOffersFound: "Nessuna offerta trovata corrispondente alla tua ricerca.",
    clearSearch: "Cancella Ricerca",
    // NotFound
    pageNotFound: "Ops! Pagina non trovata",
    returnToHome: "Torna alla Home",
    // Auth
    welcomeBack: "Bentornato",
    signInToContinue: "Accedi per continuare su weasydeal",
    createAccount: "Crea Account",
    joinViewDeal: "Unisciti a weasydeal e inizia a collaborare",
    email: "Email",
    password: "Password",
    confirmPassword: "Conferma Password",
    accountType: "Tipo di Account",
    creator: "Creator",
    business: "Azienda",
    loggingIn: "Accesso in corso...",
    creatingAccount: "Creazione account...",
    loginSuccess: "Accesso riuscito!",
    accountCreated: "Account creato con successo!",
    // Create Offer
    createNewOffer: "Crea Nuova Offerta",
    backToDashboard: "Torna al Pannello",
    offerTitle: "Titolo Offerta",
    offerTitlePlaceholder: "es., Recensione Prodotto, Video Unboxing...",
    description: "Descrizione",
    descriptionPlaceholder: "Descrivi cosa stai cercando...",
    category: "Categoria",
    selectCategory: "Seleziona una categoria",
    fitness: "Fitness",
    technology: "Tecnologia",
    fashion: "Moda",
    lifestyle: "Stile di Vita",
    gaming: "Gaming",
    food: "Cibo e Bevande",
    requiredViewsLabel: "Visualizzazioni Richieste",
    platformLabel: "Piattaforma",
    selectPlatform: "Seleziona piattaforma",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Tipo di Ricompensa",
    selectRewardType: "Seleziona tipo di ricompensa",
    cashPerView: "Denaro per Visualizzazione/Video",
    discount: "Codice Sconto",
    freeGift: "Regalo Gratuito",
    cashAmount: "Importo in Denaro (€)",
    discountCode: "Codice Sconto",
    discountValue: "Valore Sconto (%)",
    giftDescription: "Descrizione Regalo",
    publishOffer: "Pubblica Offerta",
    offerCreated: "Offerta creata con successo!",
    // Onboarding
    chooseYourPath: "Scegli il Tuo Percorso",
    areYouCreator: "Sei un creator in cerca di accordi con brand, o un'azienda in cerca di influencer?",
    creatorTitle: "Sono un Creator",
    creatorDesc: "Ricevi un compenso per creare contenuti per i brand che ami",
    creatorFeature1: "Sfoglia offerte di collaborazione pagate",
    creatorFeature2: "Pagamenti sicuri tramite escrow",
    creatorFeature3: "Costruisci il tuo portfolio",
    continueAsCreator: "Continua come Creator",
    businessTitle: "Sono un'Azienda",
    businessDesc: "Trova creator autentici per promuovere il tuo brand",
    businessFeature1: "Pubblica opportunità di collaborazione",
    businessFeature2: "Accedi a creator verificati",
    businessFeature3: "Monitora le prestazioni delle campagne",
    continueAsBusiness: "Continua come Azienda",
    alreadyHaveAccount: "Hai già un account?",
    // Support
    supportTitle: "Come Possiamo Aiutarti?",
    supportDescription: "Contatta il nostro team o sfoglia le domande comuni",
    getInTouch: "Mettiti in Contatto",
    whatsappSupport: "Supporto WhatsApp",
    chatWithUs: "Chatta direttamente con noi",
    emailSupport: "Supporto Email",
    sendEmail: "Inviaci un'email",
    frequentlyAsked: "Domande Frequenti",
    stillNeedHelp: "Hai Ancora Bisogno di Aiuto?",
    contactSupport: "Contatta il Supporto",
    chatNotFound: "Chat Non Trovata",
    active: "Attivo",
    typeMessage: "Scrivi il tuo messaggio...",
    accessDenied: "Accesso Negato",
    onlyBusinessCanPost: "Solo gli account aziendali possono creare offerte.",
    offerPostedSuccess: "La tua offerta è stata pubblicata con successo.",
    postOfferDescription: "Pubblica un'offerta per i creator per candidarsi e promuovere la tua azienda",
    cashAmountDesc: "I creator verranno pagati in base alle visualizzazioni verificate dopo 14 giorni",
    discountDetails: "Dettagli Sconto",
    discountPlaceholder: "Es., 20% di sconto su tutti i prodotti, codice: CREATOR20",
    giftPlaceholder: "Descrivi il prodotto o regalo gratuito...",
    creatorFeature4: "Funziona con TikTok, Instagram e YouTube",
    businessFeature4: "Verifica i risultati prima del rilascio del pagamento",
    emailUs: "Inviaci un'Email",
    chatOnWhatsApp: "Chatta su WhatsApp",
    supportAvailability: "Il nostro team di supporto è disponibile dal lunedì al venerdì, 9:00 - 18:00 CET",
    sendEmailButton: "Invia Email",
    totalRewardAmount: "Importo Ricompensa Totale (€)",
    totalRewardDesc: "Importo totale da pagare se il creatore raggiunge il 100% o più delle visualizzazioni richieste. I creatori guadagnano proporzionalmente in base alle visualizzazioni raggiunte (es. 50% delle visualizzazioni = 50% della ricompensa, massimo 100%)",
    calculatedEarnings: "Guadagni Calcolati",
    ofTarget: "dell'obiettivo",
    actualViews: "visualizzazioni effettive",
    freeGiftDetails: "Dettagli Regalo Gratuito",
    totalReward: "Ricompensa Totale",
    learnHowItWorks: "Scopri Come Funziona",
    seeFullProcess: "Vedi il Processo Completo",
    // How It Works page
    transparentMarketplace: "Marketplace Trasparente",
    howItWorksHero: "Il Tuo Viaggio dalla Scoperta al Pagamento",
    howItWorksSubtitle: "Una piattaforma trasparente e sicura dove creator e aziende costruiscono partnership autentiche basate su prestazioni verificate.",
    whyViewDealWorks: "Perché weasydeal Funziona",
    whyViewDealWorksDesc: "Costruito su fiducia, trasparenza e compensazione equa per tutte le parti.",
    secureEscrowFeature: "Tutti i fondi sono trattenuti in escrow sicuro fino alla verifica del contenuto, proteggendo sia creator che aziende.",
    percentageBasedTitle: "Ricompense Basate su Percentuale",
    percentageBasedFeature: "Guadagna in base alle prestazioni effettive. Raggiungi il 50% delle visualizzazioni, guadagna il 50% della ricompensa. Supera gli obiettivi, guadagna l'intera ricompensa.",
    instantMatchingTitle: "Abbinamento Istantaneo",
    instantMatchingFeature: "Connettiti con i creator o brand giusti in minuti attraverso il nostro sistema di abbinamento intelligente.",
    verifiedPaymentsTitle: "Pagamenti Verificati",
    verifiedPaymentsFeature: "Periodo di verifica di 14 giorni garantisce coinvolgimento autentico prima del rilascio del pagamento.",
    creatorJourneyTitle: "Il Tuo Viaggio da Creator",
    creatorJourneyDesc: "Dalla scoperta delle opportunità fino al pagamento - ecco come i creator hanno successo su weasydeal.",
    step: "Passo",
    creatorStep1Title: "Crea il Tuo Profilo",
    creatorStep1Desc: "Registrati in pochi minuti e mostra il tuo portfolio di contenuti, dati demografici del pubblico e tassi di coinvolgimento.",
    creatorStep2Title: "Sfoglia e Candidati alle Offerte",
    creatorStep2Desc: "Esplora collaborazioni con brand verificati che corrispondono alla tua nicchia, dimensione del pubblico e stile di contenuto.",
    creatorStep3Title: "Ottieni l'Approvazione",
    creatorStep3Desc: "I brand esaminano la tua candidatura e approvano i creator che si allineano con i loro obiettivi di campagna.",
    creatorStep4Title: "Crea e Invia Contenuto",
    creatorStep4Desc: "Produci contenuti autentici seguendo le linee guida del brand. Pubblica sulla tua piattaforma e invia la prova con il conteggio delle visualizzazioni.",
    creatorStep5Title: "Guadagna la Tua Ricompensa",
    creatorStep5Desc: "Dopo la verifica di 14 giorni, guadagna in base alle visualizzazioni effettive raggiunte. Fondi rilasciati automaticamente dall'escrow.",
    startAsCreator: "Inizia come Creator",
    businessJourneyTitle: "Il Tuo Viaggio Aziendale",
    businessJourneyDesc: "Lancia campagne, trova creator autentici e paga solo per risultati verificati.",
    businessStep1Title: "Pubblica la Tua Campagna",
    businessStep1Desc: "Definisci la tua offerta, imposta obiettivi di visualizzazione, importo totale della ricompensa e specifica i requisiti per i creator.",
    businessStep2Title: "Esamina le Candidature",
    businessStep2Desc: "I creator si candidano alla tua campagna. Esamina i loro profili, lavori passati e metriche di coinvolgimento.",
    businessStep3Title: "Approva i Creator",
    businessStep3Desc: "Seleziona i creator più adatti per il tuo brand. Finanzia l'escrow per garantire la collaborazione.",
    businessStep4Title: "Monitora le Prestazioni",
    businessStep4Desc: "Monitora le sottomissioni di contenuti e il conteggio delle visualizzazioni in tempo reale tramite il tuo pannello.",
    businessStep5Title: "Risultati Verificati",
    businessStep5Desc: "Dopo la verifica di 14 giorni, il pagamento viene rilasciato in base alle visualizzazioni effettive raggiunte. Trasparenza totale garantita.",
    startAsBusiness: "Inizia come Azienda",
    trustSecurityTitle: "Fiducia e Sicurezza Integrate",
    trustSecurityDesc: "weasydeal protegge sia creator che aziende con misure di sicurezza leader del settore e processi trasparenti.",
    escrowProtection: "100% protezione escrow per tutti gli accordi",
    verifiedMetrics: "Conteggi di visualizzazioni e metriche di coinvolgimento verificati",
    disputeResolution: "Processo equo di risoluzione delle controversie",
    transparentPayments: "Calcoli di pagamento trasparenti",
    daysVerification: "Giorni di Verifica",
    escrowProtected: "Protetto da Escrow",
    activeUsers: "Utenti Attivi",
    paidOut: "Pagato",
    readyToTransform: "Pronto a Trasformare le Tue Collaborazioni?",
    readyToTransformDesc: "Unisciti al marketplace dove creator e brand si connettono attraverso partnership autentiche e risultati verificati.",
    joinNow: "Unisciti Ora - È Gratis",
    faqQuestion1: "Come funziona il sistema di pagamento escrow?",
    faqAnswer1: "Quando un brand accetta la tua candidatura, finanzia l'escrow. Il pagamento è trattenuto in sicurezza fino a quando invii la prova delle visualizzazioni e viene verificato dopo 14 giorni.",
    faqQuestion2: "Quale prova devo inviare?",
    faqAnswer2: "Devi inviare uno screenshot del conteggio delle visualizzazioni e l'URL del tuo contenuto. Il conteggio delle visualizzazioni deve essere verificato 14 giorni dopo la pubblicazione.",
    faqQuestion3: "Quali piattaforme sono supportate?",
    faqAnswer3: "Attualmente, weasydeal supporta TikTok, Instagram e YouTube per la verifica delle visualizzazioni.",
    faqQuestion4: "Cosa succede se non raggiungo le visualizzazioni richieste?",
    faqAnswer4: "Se il conteggio delle visualizzazioni non soddisfa i requisiti dopo 14 giorni, il brand può scegliere di rilasciare un pagamento parziale o restituire l'importo dell'escrow.",
    faqQuestion5: "weasydeal è disponibile fuori dall'UE?",
    faqAnswer5: "Attualmente, weasydeal opera esclusivamente all'interno dell'Unione Europea per garantire la conformità alle normative UE.",
  },
  es: {
    // Navbar
    browseOffers: "Ver Ofertas",
    dashboard: "Panel",
    postOffer: "Publicar Oferta",
    support: "Soporte",
    signIn: "Iniciar Sesión",
    getStarted: "Comenzar",
    // Homepage
    heroTitle: "Conecta Creadores con Marcas",
    heroTitleHighlight: "A Través de Vistas",
    heroDescription: "El marketplace de la UE donde las marcas publican ofertas, los creadores entregan contenido y los pagos fluyen de forma segura a través del depósito en garantía después de recuentos de vistas verificados.",
    startCreatingDeals: "Comienza a Crear Acuerdos",
    secureEscrow: "Depósito Seguro",
    dayVerification: "Verificación de 14 Días",
    whyChoose: "¿Por Qué Elegir weasydeal?",
    whyChooseDescription: "Construido para la economía de creadores con confianza y transparencia en su núcleo",
    fairPricing: "Precios Justos",
    fairPricingDesc: "Establece tus propias tarifas como €1 por 1,000 vistas. Transparente y flexible.",
    secureEscrowTitle: "Depósito Seguro",
    secureEscrowDesc: "Fondos retenidos de forma segura hasta que se entregue la prueba verificada de vistas.",
    viewVerification: "Verificación de Vistas",
    viewVerificationDesc: "El período de verificación de 14 días garantiza un compromiso auténtico.",
    quickMatching: "Emparejamiento Rápido",
    quickMatchingDesc: "Encuentra los creadores o marcas perfectas en minutos, no días.",
    howItWorks: "Cómo Funciona",
    howItWorksDescription: "Cinco pasos simples desde la oferta hasta el pago",
    step1Title: "Crea Tu Perfil",
    step1Desc: "Regístrate como creador o empresa",
    step2Title: "Explora o Publica Ofertas",
    step2Desc: "Encuentra acuerdos o crea campañas",
    step3Title: "Pago Seguro",
    step3Desc: "Fondos retenidos en depósito por seguridad",
    step4Title: "Entrega Contenido",
    step4Desc: "Los creadores publican y envían pruebas",
    step5Title: "Recibe el Pago",
    step5Desc: "Pago liberado después de la verificación",
    readyToStart: "¿Listo para Comenzar?",
    readyToStartDesc: "Únete a miles de creadores y marcas construyendo asociaciones auténticas a través de weasydeal",
    createYourAccount: "Crea Tu Cuenta",
    forCreators: "Para Creadores",
    forBrands: "Para Marcas",
    postAnOffer: "Publicar una Oferta",
    manageCampaigns: "Gestionar Campañas",
    helpCenter: "Centro de Ayuda",
    contactUs: "Contáctanos",
    footerText: "© 2025 weasydeal. Marketplace europeo para creadores y marcas.",
    // Dashboard
    creatorDashboard: "Panel de Creador",
    activeDeals: "Acuerdos Activos",
    totalEarnings: "Ganancias Totales",
    pendingPayment: "Pago Pendiente",
    totalViews: "Vistas Totales",
    myApplications: "Mis Solicitudes",
    submissions: "Envíos",
    accepted: "Aceptado",
    pendingReview: "Revisión Pendiente",
    proofSubmitted: "Prueba Enviada",
    verifying: "Verificando",
    completed: "Completado",
    openChat: "Abrir Chat",
    submitProof: "Enviar Prueba",
    submitProofTitle: "Enviar Prueba de Rendimiento",
    contentURL: "URL del Contenido",
    screenshotUpload: "Subir Captura de Pantalla",
    viewCount: "Conteo de Vistas",
    awaitingReview: "En Espera de Revisión",
    viewSubmission: "Ver Envío",
    submitted: "Enviado",
    proofURL: "URL de Prueba",
    viewContent: "Ver Contenido",
    awaitingVerification: "Esperando verificación. El pago se liberará una vez aprobado.",
    // Offer Detail
    backToOffers: "Volver a Ofertas",
    offerNotFound: "Oferta No Encontrada",
    escrowFunded: "Financiado en Depósito",
    aboutThisOffer: "Acerca de Esta Oferta",
    requirements: "Requisitos",
    reward: "Recompensa",
    requiredViews: "Vistas Requeridas",
    timeframe: "Plazo",
    platform: "Plataforma",
    applications: "Solicitudes",
    applyNow: "Aplicar Ahora",
    howItWorksTitle: "Cómo Funciona",
    applyToOffer: "Aplicar a esta oferta",
    waitForApproval: "Esperar la aprobación de la empresa",
    createAndPost: "Crear y publicar contenido",
    submitProofAfter: "Enviar prueba después de 14 días",
    getPaidFromEscrow: "Recibir pago del depósito",
    applicationSubmitted: "¡Solicitud Enviada!",
    businessWillReview: "La empresa revisará tu solicitud pronto.",
    // Offers
    findPerfectDeals: "Encuentra Tus Acuerdos de Colaboración Perfectos",
    findPerfectDealsDesc: "Explora oportunidades de las mejores marcas de la UE. Aplica, crea contenido y recibe pagos a través de depósito seguro.",
    searchOffers: "Buscar ofertas...",
    views: "vistas",
    funded: "Financiado",
    viewDetailsApply: "Ver Detalles y Aplicar",
    noOffersFound: "No se encontraron ofertas que coincidan con tu búsqueda.",
    clearSearch: "Limpiar Búsqueda",
    // NotFound
    pageNotFound: "¡Ups! Página no encontrada",
    returnToHome: "Volver al Inicio",
    // Auth
    welcomeBack: "Bienvenido de Nuevo",
    signInToContinue: "Inicia sesión para continuar en weasydeal",
    createAccount: "Crear Cuenta",
    joinViewDeal: "Únete a weasydeal y comienza a colaborar",
    email: "Correo Electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar Contraseña",
    accountType: "Tipo de Cuenta",
    creator: "Creador",
    business: "Empresa",
    loggingIn: "Iniciando sesión...",
    creatingAccount: "Creando cuenta...",
    loginSuccess: "¡Inicio de sesión exitoso!",
    accountCreated: "¡Cuenta creada con éxito!",
    // Create Offer
    createNewOffer: "Crear Nueva Oferta",
    backToDashboard: "Volver al Panel",
    offerTitle: "Título de la Oferta",
    offerTitlePlaceholder: "ej., Reseña de Producto, Video Unboxing...",
    description: "Descripción",
    descriptionPlaceholder: "Describe lo que estás buscando...",
    category: "Categoría",
    selectCategory: "Seleccionar una categoría",
    fitness: "Fitness",
    technology: "Tecnología",
    fashion: "Moda",
    lifestyle: "Estilo de Vida",
    gaming: "Gaming",
    food: "Comida y Bebida",
    requiredViewsLabel: "Vistas Requeridas",
    platformLabel: "Plataforma",
    selectPlatform: "Seleccionar plataforma",
    instagram: "Instagram",
    youtube: "YouTube",
    tiktok: "TikTok",
    rewardType: "Tipo de Recompensa",
    selectRewardType: "Seleccionar tipo de recompensa",
    cashPerView: "Dinero por Vista/Video",
    discount: "Código de Descuento",
    freeGift: "Regalo Gratis",
    cashAmount: "Cantidad en Efectivo (€)",
    discountCode: "Código de Descuento",
    discountValue: "Valor del Descuento (%)",
    giftDescription: "Descripción del Regalo",
    publishOffer: "Publicar Oferta",
    offerCreated: "¡Oferta creada con éxito!",
    // Onboarding
    chooseYourPath: "Elige Tu Camino",
    areYouCreator: "¿Eres un creador buscando acuerdos con marcas, o una empresa buscando influencers?",
    creatorTitle: "Soy un Creador",
    creatorDesc: "Recibe pago por crear contenido para marcas que amas",
    creatorFeature1: "Explora ofertas de colaboración pagadas",
    creatorFeature2: "Pagos seguros a través de depósito",
    creatorFeature3: "Construye tu portafolio",
    continueAsCreator: "Continuar como Creador",
    businessTitle: "Soy una Empresa",
    businessDesc: "Encuentra creadores auténticos para promocionar tu marca",
    businessFeature1: "Publicar oportunidades de colaboración",
    businessFeature2: "Acceder a creadores verificados",
    businessFeature3: "Rastrear rendimiento de campañas",
    continueAsBusiness: "Continuar como Empresa",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    // Support
    supportTitle: "¿Cómo Podemos Ayudarte?",
    supportDescription: "Ponte en contacto con nuestro equipo o explora preguntas comunes",
    getInTouch: "Ponte en Contacto",
    whatsappSupport: "Soporte WhatsApp",
    chatWithUs: "Chatea directamente con nosotros",
    emailSupport: "Soporte por Correo",
    sendEmail: "Envíanos un correo",
    frequentlyAsked: "Preguntas Frecuentes",
    stillNeedHelp: "¿Aún Necesitas Ayuda?",
    contactSupport: "Contactar Soporte",
    chatNotFound: "Chat No Encontrado",
    active: "Activo",
    typeMessage: "Escribe tu mensaje...",
    accessDenied: "Acceso Denegado",
    onlyBusinessCanPost: "Solo las cuentas empresariales pueden crear ofertas.",
    offerPostedSuccess: "Tu oferta se ha publicado con éxito.",
    postOfferDescription: "Publica una oferta para que los creadores se postulen y promocionen tu negocio",
    cashAmountDesc: "Los creadores recibirán el pago según las vistas verificadas después de 14 días",
    discountDetails: "Detalles del Descuento",
    discountPlaceholder: "Ej., 20% de descuento en todos los productos, código: CREATOR20",
    giftPlaceholder: "Describe el producto o regalo gratuito...",
    creatorFeature4: "Funciona con TikTok, Instagram y YouTube",
    businessFeature4: "Verifica los resultados antes de liberar el pago",
    emailUs: "Envíanos un Email",
    chatOnWhatsApp: "Chatea en WhatsApp",
    supportAvailability: "Nuestro equipo de soporte está disponible de lunes a viernes, 9 AM - 6 PM CET",
    sendEmailButton: "Enviar Email",
    totalRewardAmount: "Monto Total de Recompensa (€)",
    totalRewardDesc: "Monto total a pagar si el creador alcanza el 100% o más de las vistas requeridas. Los creadores ganan proporcionalmente según las vistas alcanzadas (ej. 50% de vistas = 50% de recompensa, máximo 100%)",
    calculatedEarnings: "Ganancias Calculadas",
    ofTarget: "del objetivo",
    actualViews: "vistas reales",
    freeGiftDetails: "Detalles del Regalo Gratuito",
    totalReward: "Recompensa Total",
    learnHowItWorks: "Aprende Cómo Funciona",
    seeFullProcess: "Ver el Proceso Completo",
    // How It Works page
    transparentMarketplace: "Marketplace Transparente",
    howItWorksHero: "Tu Viaje desde el Descubrimiento hasta el Pago",
    howItWorksSubtitle: "Una plataforma transparente y segura donde creadores y empresas construyen asociaciones auténticas respaldadas por rendimiento verificado.",
    whyViewDealWorks: "Por Qué weasydeal Funciona",
    whyViewDealWorksDesc: "Construido sobre confianza, transparencia y compensación justa para todas las partes.",
    secureEscrowFeature: "Todos los fondos se mantienen en depósito seguro hasta que se verifique el contenido, protegiendo tanto a creadores como a empresas.",
    percentageBasedTitle: "Recompensas Basadas en Porcentaje",
    percentageBasedFeature: "Gana según el rendimiento real. Alcanza el 50% de las vistas, gana el 50% de la recompensa. Supera los objetivos, gana la recompensa completa.",
    instantMatchingTitle: "Emparejamiento Instantáneo",
    instantMatchingFeature: "Conéctate con los creadores o marcas correctos en minutos a través de nuestro sistema de emparejamiento inteligente.",
    verifiedPaymentsTitle: "Pagos Verificados",
    verifiedPaymentsFeature: "Período de verificación de 14 días garantiza compromiso auténtico antes de la liberación del pago.",
    creatorJourneyTitle: "Tu Viaje como Creador",
    creatorJourneyDesc: "Desde descubrir oportunidades hasta recibir el pago - así es como los creadores tienen éxito en weasydeal.",
    step: "Paso",
    creatorStep1Title: "Crea Tu Perfil",
    creatorStep1Desc: "Regístrate en minutos y muestra tu portafolio de contenido, demografía de audiencia y tasas de compromiso.",
    creatorStep2Title: "Explora y Aplica a Ofertas",
    creatorStep2Desc: "Explora colaboraciones con marcas verificadas que coincidan con tu nicho, tamaño de audiencia y estilo de contenido.",
    creatorStep3Title: "Obtén la Aprobación",
    creatorStep3Desc: "Las marcas revisan tu aplicación y aprueban a los creadores que se alinean con sus objetivos de campaña.",
    creatorStep4Title: "Crea y Envía Contenido",
    creatorStep4Desc: "Produce contenido auténtico siguiendo las pautas de la marca. Publica en tu plataforma y envía prueba con conteo de vistas.",
    creatorStep5Title: "Gana Tu Recompensa",
    creatorStep5Desc: "Después de la verificación de 14 días, gana según las vistas reales alcanzadas. Fondos liberados automáticamente desde el depósito.",
    startAsCreator: "Comenzar como Creador",
    businessJourneyTitle: "Tu Viaje Empresarial",
    businessJourneyDesc: "Lanza campañas, encuentra creadores auténticos y paga solo por resultados verificados.",
    businessStep1Title: "Publica Tu Campaña",
    businessStep1Desc: "Define tu oferta, establece objetivos de vistas, monto total de recompensa y especifica requisitos para creadores.",
    businessStep2Title: "Revisa Aplicaciones",
    businessStep2Desc: "Los creadores aplican a tu campaña. Revisa sus perfiles, trabajos anteriores y métricas de compromiso.",
    businessStep3Title: "Aprueba Creadores",
    businessStep3Desc: "Selecciona los creadores más adecuados para tu marca. Financia el depósito para asegurar la colaboración.",
    businessStep4Title: "Rastrea el Rendimiento",
    businessStep4Desc: "Monitorea las presentaciones de contenido y el conteo de vistas en tiempo real a través de tu panel.",
    businessStep5Title: "Resultados Verificados",
    businessStep5Desc: "Después de la verificación de 14 días, el pago se libera según las vistas reales alcanzadas. Transparencia total garantizada.",
    startAsBusiness: "Comenzar como Empresa",
    trustSecurityTitle: "Confianza y Seguridad Integradas",
    trustSecurityDesc: "weasydeal protege tanto a creadores como a empresas con medidas de seguridad líderes en la industria y procesos transparentes.",
    escrowProtection: "100% protección de depósito para todos los acuerdos",
    verifiedMetrics: "Conteos de vistas y métricas de compromiso verificados",
    disputeResolution: "Proceso justo de resolución de disputas",
    transparentPayments: "Cálculos de pago transparentes",
    daysVerification: "Días de Verificación",
    escrowProtected: "Protegido por Depósito",
    activeUsers: "Usuarios Activos",
    paidOut: "Pagado",
    readyToTransform: "¿Listo para Transformar Tus Colaboraciones?",
    readyToTransformDesc: "Únete al marketplace donde creadores y marcas se conectan a través de asociaciones auténticas y resultados verificados.",
    joinNow: "Únete Ahora - Es Gratis",
    faqQuestion1: "¿Cómo funciona el sistema de pago en depósito?",
    faqAnswer1: "Cuando una marca acepta tu solicitud, financian el depósito. El pago se mantiene seguro hasta que envíes la prueba de vistas y sea verificada después de 14 días.",
    faqQuestion2: "¿Qué prueba debo enviar?",
    faqAnswer2: "Debes enviar una captura de pantalla de tu conteo de vistas y la URL de tu contenido. El conteo de vistas debe verificarse 14 días después de publicar.",
    faqQuestion3: "¿Qué plataformas son compatibles?",
    faqAnswer3: "Actualmente, weasydeal admite TikTok, Instagram y YouTube para la verificación de vistas.",
    faqQuestion4: "¿Qué pasa si no alcanzo las vistas requeridas?",
    faqAnswer4: "Si el conteo de vistas no cumple con el requisito después de 14 días, la marca puede optar por liberar un pago parcial o devolver el monto del depósito.",
    faqQuestion5: "¿weasydeal está disponible fuera de la UE?",
    faqAnswer5: "Actualmente, weasydeal opera exclusivamente dentro de la Unión Europea para garantizar el cumplimiento de las regulaciones de la UE.",
  },
};

const detectUserLanguage = (): Language => {
  const stored = localStorage.getItem("userLanguage");
  if (stored && (stored === "en" || stored === "it" || stored === "es")) {
    return stored as Language;
  }

  const browserLang = navigator.language.toLowerCase();
  if (browserLang.startsWith("it")) return "it";
  if (browserLang.startsWith("es")) return "es";
  return "en";
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(detectUserLanguage);

  useEffect(() => {
    localStorage.setItem("userLanguage", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
